name: flutter_parsed_text_field
description: A flutter package which lets you use styled @mentions and \#hashtags with twitter-like
  suggestions in your TextField.
version: 0.1.8
homepage: https://github.com/Kulture-Inc/flutter_parsed_text_field

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dartx: ^0.7.1
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: